### ISSUE TITLE
Node.js v12 compatibility

### ISSUE THREAD

**Issue by jpawlowski** [dominikkarall/gassistant-fhem#1]
It seems this module is not compatible with new LTS Node.js v12 since it (implicitly) depends on a old version of grpc (1.20.0).

See build results here:
https://travis-ci.com/fhem/fhem-docker/jobs/248272843

According to [this comment](https://github.com/grpc/grpc-node/issues/834#issuecomment-509952117), one should simply use grpc >= 1.20.2

**Comment by fhempy** [comment]
Thank you for the hint!

Can you please try adding grpc 1.24 to the package.json and let me know if it works for you?
"grpc": "^1.24.2"

**Comment by fhempy** [comment]
Fixed with new grpc release
