### ISSUE TITLE
Delete Auth0 User

### ISSUE THREAD

**Issue by petterpet** [dominikkarall/gassistant-fhem#3]
I won't use FHEM anymore. How can I delete my Auth0-User?

**Comment by fhempy** [comment]
Just do set gassistant unregister in FHEM.

**Comment by petterpet** [comment]
That doesn't help. I'm still able to login in Auth0 with my mail address and password.

**Comment by fhempy** [comment]
Please send me an email from the email address you would like to delete and I'm going to delete it manually.

**Comment by petterpet** [comment]
Done
